
sudo: true

services:
  - docker

env:
  COMPOSE_VERSION: 1.23.1

before_install:
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin
 - npm install -g eslint

script:
  - eslint .
  - docker-compose build
  - docker-compose up -d
  - docker-compose run ores-api pip install -r test-requirements.txt
  - docker-compose run ores-api flake8 .
  - sleep 5
  - docker-compose run ores-api ./utility test_api http://localhost:8080 --debug
  - docker-compose run ores-api py.test --cov=ores

after_success:
  - codecov

dist: trusty
notifications:
  irc:
    channels:
      - "chat.freenode.net#wikimedia-ai"
    on_success: change
    on_failure: change
    template:
      - "%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} %{build_url}"
